FreeRTOS/coreMQTT-Agent

source/include/mqtt_agent.h, source/mqtt_agent.c, source/mqtt_agent_command_functions.c, test/unit-test/CMakeLists.txt, test/unit-test/mqtt_agent_utest.c
*Description*:
Adds input validation to most MQTT Agent API functions, and unit tests for the following:
* `MQTTAgent_Subscribe`
* `MQTTAgent_Unsubscribe`
* `MQTTAgent_ProcessLoop`
* `MQTTAgent_Disconnect`
* `MQTTAgent_Ping`
* `MQTTAgent_Terminate`
In the process of writing tests, some changes were made to the source code:
* Some more `NULL` checks.
* `assert`s in favor of `if` checks where the parameter had already been checked for `NULL`
* Some missed calls in `MQTTAgentCommand_Connect` to resume sessions.
`MQTTAgent_Connect` and `MQTTAgent_Publish` still need unit tests, however I thought those should be added later lest this PR grow too large. Coverage of `mqtt_agent.c` is around 33%.
=> Add input validation and some unit tests

test/cbmc/include/agent_command_pool_stubs.h, test/cbmc/include/agent_message_stubs.h, test/cbmc/include/get_time_stub.h, test/cbmc/include/incoming_publish_callback_stub.h, test/cbmc/include/mqtt_agent_cbmc_state.h, test/cbmc/include/network_interface_stubs.h, test/cbmc/proofs/MQTTAgent_Disconnect/MQTTAgent_Disconnect_harness.c, test/cbmc/proofs/MQTTAgent_Disconnect/Makefile, test/cbmc/proofs/MQTTAgent_Disconnect/README.md, test/cbmc/proofs/MQTTAgent_Disconnect/cbmc-proof.txt, test/cbmc/proofs/MQTTAgent_Disconnect/cbmc-viewer.json, test/cbmc/sources/mqtt_agent_cbmc_state.c, test/cbmc/stubs/agent_command_pool_stubs.c, test/cbmc/stubs/agent_message_stubs.c, test/cbmc/stubs/get_time_stub.c, test/cbmc/stubs/incoming_publish_callback_stub.c, test/cbmc/stubs/network_interface_stubs.c
CBMC proof for MQTTAgent_Disconnect.
The errors are fixed in the PR #7. This proof should be merged only after the PR #7 is merged and the branch is rebased.
=> CBMC proof for MQTTAgent_Disconnect

source/include/mqtt_agent.h, source/mqtt_agent.c, source/mqtt_agent_command_functions.c, tools/coverity/misra.config
*Description*:
Resolves most MISRA warnings, except for:
- 8.7 (external linkage, not resolvable)
- 8.13 (adding const everywhere)
- A few 17.7 (unused return of non void).
There are some fixes pending for the agent that will cause some code to be rearranged and some unmodified pointers to be modified, so fixing the remaining warnings right now is premature.
Also adds a MISRA config file.
=> Resolve most MISRA warnings

source/mqtt_agent.c, source/mqtt_agent_command_functions.c, test/CMakeLists.txt
*Description*:
The `releaseCommand` function pointer needs to be called whenever a command has terminated, otherwise there will be a memory leak as the allocated command is never released. This adds the call to `releaseCommand` to all cases when a command is terminated, which was previously missing for error cases.
=> Release commands when canceled

test/cbmc/include/mqtt_agent_cbmc_state.h, test/cbmc/proofs/MQTTAgentCommand_Connect/MQTTAgentCommand_Connect_harness.c, test/cbmc/proofs/MQTTAgentCommand_Connect/Makefile, test/cbmc/proofs/MQTTAgentCommand_Connect/README.md, test/cbmc/proofs/MQTTAgentCommand_Connect/cbmc-proof.txt, test/cbmc/proofs/MQTTAgentCommand_Connect/cbmc-viewer.json, test/cbmc/proofs/MQTTAgentCommand_Disconnect/MQTTAgentCommand_Disconnect_harness.c, test/cbmc/proofs/MQTTAgentCommand_Disconnect/Makefile, test/cbmc/proofs/MQTTAgentCommand_Disconnect/README.md, test/cbmc/proofs/MQTTAgentCommand_Disconnect/cbmc-proof.txt, test/cbmc/proofs/MQTTAgentCommand_Disconnect/cbmc-viewer.json, test/cbmc/proofs/MQTTAgentCommand_Ping/MQTTAgentCommand_Ping_harness.c, test/cbmc/proofs/MQTTAgentCommand_Ping/Makefile, test/cbmc/proofs/MQTTAgentCommand_Ping/README.md, test/cbmc/proofs/MQTTAgentCommand_Ping/cbmc-proof.txt, test/cbmc/proofs/MQTTAgentCommand_Ping/cbmc-viewer.json, test/cbmc/proofs/MQTTAgentCommand_ProcessLoop/MQTTAgentCommand_ProcessLoop_harness.c, test/cbmc/proofs/MQTTAgentCommand_ProcessLoop/Makefile, test/cbmc/proofs/MQTTAgentCommand_ProcessLoop/README.md, test/cbmc/proofs/MQTTAgentCommand_ProcessLoop/cbmc-proof.txt, test/cbmc/proofs/MQTTAgentCommand_ProcessLoop/cbmc-viewer.json, test/cbmc/sources/mqtt_agent_cbmc_state.c
This PR contains the cbmc proofs for the following MQTTAgentCommnad_functions:
1. MQTTAgentCommnad_Connect
2. MQTTAgentCommnad_Disconnect
3. MQTTAgentCommnad_Ping
4. MQTTAgentCommnad_ProcessLoop
=> [MQTT Agent ]Cbmc proofs for Connect, Disconnect, Ping and ProcessLoop Command functions

.github/workflows/ci.yml, source/include/mqtt_agent.h, source/include/mqtt_agent_command_functions.h, source/mqtt_agent.c, source/mqtt_agent_command_functions.c, test/unit-test/mqtt_agent_utest.c
*Description*:
Fixes build warnings, increases coverage, and addresses some MISRA violations. Each change is a separate commit.
* Fix build warnings as a result of using designated initializers for declaring the function pointer. This adds a preprocessor check for C99 before using the designated initializers, and normal initialization if using C90. Both forms are included per Richard's request.
* Enables the `-Werror` flag for CI as all build warnings are resolved.
* Increases unit test coverage to 100% and enables the CI coverage check.
* Resolves all MISRA warnings with the current config except for 8.7 and some 8.13. 8.7 can't be resolved as API functions must be externally linked, and the remaining 8.13 warnings can't be resolved as functions must have an identical signature to the …
=> Address warnings and coverage

test/cbmc/include/mqtt_agent_cbmc_state.h, test/cbmc/proofs/MQTTAgentCommand_Publish/MQTTAgentCommand_Publish_harness.c, test/cbmc/proofs/MQTTAgentCommand_Publish/Makefile, test/cbmc/proofs/MQTTAgentCommand_Publish/README.md, test/cbmc/proofs/MQTTAgentCommand_Publish/cbmc-proof.txt, test/cbmc/proofs/MQTTAgentCommand_Publish/cbmc-viewer.json, test/cbmc/proofs/MQTTAgentCommand_Subscribe/MQTTAgentCommand_Subscribe_harness.c, test/cbmc/proofs/MQTTAgentCommand_Subscribe/Makefile, test/cbmc/proofs/MQTTAgentCommand_Subscribe/README.md, test/cbmc/proofs/MQTTAgentCommand_Subscribe/cbmc-proof.txt, test/cbmc/proofs/MQTTAgentCommand_Subscribe/cbmc-viewer.json, test/cbmc/proofs/MQTTAgentCommand_Unsubscribe/MQTTAgentCommand_Unsubscribe_harness.c, test/cbmc/proofs/MQTTAgentCommand_Unsubscribe/Makefile, test/cbmc/proofs/MQTTAgentCommand_Unsubscribe/README.md, test/cbmc/proofs/MQTTAgentCommand_Unsubscribe/cbmc-proof.txt, test/cbmc/proofs/MQTTAgentCommand_Unsubscribe/cbmc-viewer.json, test/cbmc/sources/mqtt_agent_cbmc_state.c
This PR contains the cbmc proofs for the following MQTTAgentCommand_functions:
1. MQTTAgentCommand_Publish
2. MQTTAgentCommnad_Subscribe
3. MQTTAgentCommnad_Unsubscribe
=> [MQTT Agent] Cbmc proofs for Publish, Subscribe, Unsubscribe command functions

lexicon.txt, source/include/agent_message.h, source/include/mqtt_agent.h, test/unit-test/mqtt_agent_command_functions_utest.c, test/unit-test/mqtt_agent_utest.c
*Description*:
The `void *` pointers in the messaging interface will always be `Command_t **` double pointers, so this makes that change for increased readability and compile-time type checking.
=> Change void * in interface to Command_t **

.github/workflows/release.yml
**Add a GitHub Action job to trigger a release process** which includes operations of: 
1. Deleting an existing release and tag, if the same tag is being re-released.
1. Creating and pushing the release tag to the repository 
1. Verifying the pushed tag (performing a diff with the commit ID which is tagged) 
1. Creating a ZIP for the release asset. 
1. Verifying the ZIP by performing a diff check and running unit tests on the unzipped files. 5. Creating a release on the repository for the tag, and uploading the ZIP as the release asset
The workflow can be manually triggered and takes the input values of **Commit ID** (to create a release for) and the **Version string** for tagging the release with
**Testing**
Here are example runs of the release job on my fork repository that created the …
=> Add GitHub Actions workflow to automate release

.github/workflows/ci.yml, docs/doxygen/config.doxyfile, docs/doxygen/pages.dox, source/include/mqtt_agent.h, source/include/mqtt_agent_command_functions.h, source/mqtt_agent.c
*Description*:
Adds a GitHub Actions check for doxygen documentation, and links to external MQTT documentation. Since the `Command_t` typedef and struct definition are in separate files, doxygen has issues resolving references to it. This works around it by referring to the struct itself in our docs instead of the typedef.
=> Add doxygen GA and link to MQTT documentation

docs/doxygen/pages.dox, lexicon.txt, source/include/core_mqtt_agent.h, source/include/core_mqtt_agent_command_functions.h, source/include/core_mqtt_agent_message_interface.h
*Description*:
Adds doxygen pages detailing the design of the MQTT agent, and its messaging interface. Also adds some notes to improve the documentation of functions, and a missed example code block.
=> Add more doxygen pages

source/include/core_mqtt_agent.h, test/unit-test/mqtt_agent_utest.c
*Description*:
The first parameter of the command completion callback is the command context pointer, which does not need to be `void *` and can be `MQTTAgentCommandContext_t *`.
=> Change void to MQTTAgentCommandContext_t

.github/memory_statistics_config.json, docs/doxygen/include/size_table.html
Updates the memory statistics config to use the tagging feature to tag coreMQTT files.
=> Update memory table config for tagging

README.md
*Description*:
Adds a section to the README that describes the platform-dependent features needed when implementing the messaging interface.
=> Add more porting instructions to README

.github/workflows/doxygen.yml, .github/workflows/release.yml
The doxygen action as used by other repos does not work due to the dependency on the coreMQTT docs. This generates and includes the coreMQTT docs in the coreMQTT-Agent bundle.
=> Fix doxygen generation by including coreMQTT docs

lexicon.txt, test/unit-test/config/core_mqtt_config.h
This PR updates the coreMQTT submodule pointer to point to v2.1.0 release.
It also updates one config macro name to be compatible with coreMQTT changes.
=> Update coreMQTT submodule pointer

source/core_mqtt_agent.c
The underlying integer type of an enum in C is implementation-defined. 
It may be compatible with one of: 
* char 
* unsigned integers
* signed integers
IAR Embedded Workbench decides to make the enum unsigned only to warn against checking an enum value is positive.
Other compilers may emit signed integers for the enum, so an explicit cast is needed.
=> Cast MQTTAgentCommandType_t to unsigned

README.md
Description
-----------
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> Add documentation about configuration options

MISRA.md, source/core_mqtt_agent.c, tools/coverity/misra.config
Description
-----------
Fix these MISRA violations : 
MISRA C-2012 Directive 4.6 
MISRA C-2012 Rule 11.3
MISRA C-2012 Rule 8.13 
MISRA C-2012 Rule 8.7 
MISRA C-2012 Rule 8.9
Test Steps
-----------
Run Coverity tools.
Checklist:
----------
Related Issue
-----------
=> Fix MISRA violations

.github/workflows/release.yml, manifest.yml
Description
-----------
Add SBOM Generation in release.yml
Test Steps
-----------
Successful release automation in forked branch.
Checklist:
----------
Related Issue
-----------
=> Add SBOM Generation in release.yml

CHANGELOG.md, docs/doxygen/config.doxyfile, manifest.yml, test/CMakeLists.txt
Description
-----------
Release preparation for v1.3.1
Update changelog for version v1.3.1
Update version tag in .md files and manifest files
Test Steps
-----------
Checklist:
----------
Related Issue
-----------
=> [v1.3.1] Update change log, version numbers and .md files for release

.github/.cSpellWords.txt, .github/workflows/ci.yml, README.md, docs/doxygen/include/size_table.md, manifest.yml, source/core_mqtt_agent.c, source/include/core_mqtt_agent_config_defaults.h, test/unit-test/cmock_opaque_types.h, test/unit-test/mqtt_agent_utest.c, tools/cmock/coverage.cmake, tools/cmock/create_test.cmake, tools/cmock/project.yml
Description
-----------
- Updates the coreMQTT submodule pointer to the latest commit of the library.
- Includes the `core_mqtt_config_defaults.h` file in the `core_mqtt_agent_config_defaults.h`. 
- This is done because the older version of coreMQTT (v1.x.x) has `core_mqtt_config.h` included in the `core_mqtt.h` file whose macros is used by a couple of more files like `freertos_command_pool.c` in some old demos (like the old OTA demos). But in the new version this includes is removed from the `core_mqtt.h` file and added in the `core_mqtt_config_defaults.h` file. A simple solution to this problem was to add the `core_mqtt_config_defaults.h` in the `core_mqtt_agent_config_defaults.h` which is included in the `core_mqtt_agent.h` that is used by the files that require the macros. 
- Updates …
=> Updating the coreMQTT submodule pointer

source/core_mqtt_agent.c, source/include/core_mqtt_agent.h
Move static arrays from function MQTTAgent_Init to MQTTAgentContext_t.
Description
-----------
Move `pIncomingPublishRecords` and `pOutgoingPublishRecords` into MQTTAgentContext_t for better maintainability.
Test Steps
-----------
Execute unit-test cases
Checklist:
----------
Related Issue
-----------
#130 
=> Move static arrays from function MQTTAgent_Init to MQTTAgentContext_t.
